[package]
name = "web_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "web_server_core"
path = "src/lib.rs"


[[bin]]
name = "web_server"
path = "src/main.rs"

[dependencies]


